name: 签到领京豆

on:
  schedule:
    - cron: "00 00 * * *"

  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && pip install -r requirements.txt

      - name: run sign script
        run: python daily_sign.py
        env:
          JD_COOKIES: ${{secrets.JD_COOKIE}}
